name: Run RSI Trading Bot

on:
  workflow_dispatch:  # allows manual trigger from GitHub UI

jobs:
  run-rsi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Upgrade pip and build tools
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run RSI script
      run: |
        python RSI.py
      env: 
        auth_json: ${{ secrets.AUTH_JSON }}
      
